# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9374aa913c899d266ac3e3ad5d450923d09395aa285f63bfbecf924198313bb273935769b84a9228eb998f8fa65ea16533e110079e14769d172b67bf6a2861b3

test:
  secret_key_base: 20ffc993ad623b04e0dbf800f90bc730a732ca0069cd98a75e657f4baeece428600cc1ad8dcfe6fdb8d47b31e7b386239e62e7e28090b9f1f38bbe6d8c4a3a7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
